config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/index'

  mount Ckeditor::Engine => '/ckeditor'
  root 'goods#index'
  resources :users, :pages, :news, :goods
  resources :sessions, only: [ :new, :create, :destroy ]
  resources :categories, only: [ :index, :show, :create, :update, :destroy ]
  resources :carts, only: [ :index, :create, :destroy ]
  resources :orders, only: [ :index, :create, :destroy ]
  resources :images, only: [ :create, :destroy ]
  resources :bookmarks, only: [ :index, :create, :destroy ]
  resources :good_reviews, only: [ :create, :update, :destroy ]
  resources :likes, only: [ :create, :destroy ]
  
  resources :questions, only: [ :index, :create, :update, :destroy ]
  resources :tickets, only: [ :index, :show, :new, :create, :update, :destroy ]

  # Comments
  resources :comments, only: [ :create, :destroy ]

  # Properties
  resources :property_types, only: [ :index, :create, :update, :destroy ]
  resources :properties, only: [ :index, :create, :update, :destroy ]
  resources :property_values, only: [ :create, :update ]
  match '/categories/:cid/properties/:pid', to: 'categories#include', via: 'post'
  match '/categories/:cid/properties/:pid', to: 'categories#exclude', via: 'delete'

  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/search',  to: 'static_pages#search', via: 'get'
  match '/admin',   to: 'static_pages#admin',  via: 'get'

  get '/:href',     to: 'pages#open_url'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :admin_user, only: :admin

  def home
  end

  def search
  	q = params[:q]

  	@goods = Good.where('goods.name LIKE :l_q OR goods.description LIKE :l_q', { l_q: "%#{q}%" })
  	@news = New.where('news.title LIKE :l_q OR news.description LIKE :l_q', { l_q: "%#{q}%" })
  	@pages = Page.where('pages.title LIKE :l_q OR pages.description LIKE :l_q', { l_q: "%#{q}%" })
  end

  def admin
  	@goods 			= Good.all
  	@orders			= Order.all
  	@users 			= User.all
  	@news 			= New.all
  	@pages 			= Page.all
  	@tickets 		= Ticket.all
  	@categories 	= Category.all
  	@properties		= Property.all
  	@property_types = PropertyType.all
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_categories.html.erb
<h1>Категории</h1>
<div id="categories">
	<%= render 'categories/form', category: Category.new %>
	<ul>
		<%= render @categories %>
	</ul>
</div>

app/views/static_pages/_goods.html.erb
<h1>Товары</h1>
<%= render @goods %>

app/views/static_pages/_news.html.erb
<h1>Новости</h1>
<%= link_to 'Создать', new_news_path, class: 'label label-primary' %>
<div class="group-list">
	<%= render @news %>
</div>

app/views/static_pages/_orders.html.erb
<%= render @orders %>

app/views/static_pages/_pages.html.erb
<h1>Страницы</h1>
<%= link_to 'Создать', new_page_path, class: 'label label-primary' if admin? %>
<div class="list-group">
	<%= render @pages %>
</div>

app/views/static_pages/_properties.html.erb
<h1>Свойства</h1>
<table class="table table-hovered">
	<thead>
		<th>#</th>
		<th>Название</th>
		<th>Описание</th>
		<th>Тип</th>
		<th colspan="2">Действия</th>
	</thead>
	<%= render @properties %>
	<%= render 'properties/fields', property: Property.new %>
</table>

app/views/static_pages/_property_types.html.erb
<h1>Типы</h1>
<table class="table table-hovered">
	<thead>
		<th>#</th>
		<th>Название</th>
		<th>Описание</th>
		<th>Регулярное выражение</th>
		<th>Представление</th>
		<th colspan="2">Действия</th>
	</thead>
	<%= render @property_types %>
	<%= render 'property_types/fields', type: PropertyType.new %>
</table>

app/views/static_pages/_tickets.html.erb
<h1>Тикеты</h1>
<%= link_to 'Создать', new_ticket_path, class: 'btn btn-primary' %>
<div class="col-lg-12">
	<div class="list-group">
		<%= render @tickets %>
	</div>
</div>

app/views/static_pages/_users.html.erb
<div class="list-group">	
	<%= render @users %>
</div>

app/views/static_pages/admin.html.erb
<% provide :title, 'Администрирование' %>
<div class="container">
	<ul class="nav nav-tabs nav-info" style="margin-bottom: 15px;">
		<li><a href="#orders" data-toggle="tab">Заказы</a></li>
		<li><a href="#tickets" data-toggle="tab">Тикеты</a></li>
		<li><a href="#news" data-toggle="tab">Новости</a></li>
		<li><a href="#pages" data-toggle="tab">Страницы</a></li>
		<li><a href="#users" data-toggle="tab">Пользователи</a></li>
		<li><a href="#categories" data-toggle="tab">Категории</a></li>
		<li><a href="#goods" data-toggle="tab">Товары</a></li>
		<li><a href="#properties" data-toggle="tab">Свойства</a></li>
		<li><a href="#types" data-toggle="tab">Типы свойств</a></li>
	</ul>
	<div id="myTabContent" class="tab-content">
		<div class="tab-pane fade" id="orders">
			<%= render 'orders' %>
		</div>
		<div class="tab-pane fade" id="tickets">
			<%= render 'tickets' %>
		</div>
		<div class="tab-pane fade" id="news">
			<%= render 'news' %>
		</div>
		<div class="tab-pane fade" id="pages">
			<%= render 'pages' %>
		</div>
		<div class="tab-pane fade" id="users">
			<%= render 'users' %>
		</div>
		<div class="tab-pane fade" id="categories">
		    <%= render 'categories' %>
		</div>
		<div class="tab-pane fade" id="goods">
			<%= render 'goods' %>
		</div>
		<div class="tab-pane fade" id="properties">
			<%= render 'properties' %>
		</div>
		<div class="tab-pane fade" id="types">
			<%= render 'property_types' %>
		</div>
	</div>
</div>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Hello, World!</h1>
  </div>
</div>

app/views/static_pages/search.html.erb
<% provide :title, 'Поиск' %>
<div class="container">
	<h1>Поиск</h1>
	<div class="col-lg-12">
		<h2>Товары</h2>
		<% @goods.each do |good| %>
			<%= render 'goods/good', good: good %>
		<% end %>
	</div>
	<div class="col-lg-12">
		<h2>Новости</h2>
		<% @news.each do |n| %>
			<%= render 'news/new', new: n %>
		<% end %>
	</div>
	<div class="col-lg-12">
		<h2>Страницы</h2>
		<% @pages.each do |page| %>
			<%= render 'pages/page', page: page %>
		<% end %>
	</div>
</div>