config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/index'

  mount Ckeditor::Engine => '/ckeditor'
  root 'goods#index'
  resources :users, :pages, :news, :goods
  resources :sessions, only: [ :new, :create, :destroy ]
  resources :categories, only: [ :index, :show, :create, :update, :destroy ]
  resources :carts, only: [ :index, :create, :destroy ]
  resources :orders, only: [ :index, :create, :destroy ]
  resources :images, only: [ :create, :destroy ]
  resources :bookmarks, only: [ :index, :create, :destroy ]
  resources :good_reviews, only: [ :create, :update, :destroy ]
  resources :likes, only: [ :create, :destroy ]
  
  resources :questions, only: [ :index, :create, :update, :destroy ]
  resources :tickets, only: [ :index, :show, :new, :create, :update, :destroy ]

  # Comments
  resources :comments, only: [ :create, :destroy ]

  # Properties
  resources :property_types, only: [ :index, :create, :update, :destroy ]
  resources :properties, only: [ :index, :create, :update, :destroy ]
  resources :property_values, only: [ :create, :update ]
  match '/categories/:cid/properties/:pid', to: 'categories#include', via: 'post'
  match '/categories/:cid/properties/:pid', to: 'categories#exclude', via: 'delete'

  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/search',  to: 'static_pages#search', via: 'get'
  match '/admin',   to: 'static_pages#admin',  via: 'get'

  get '/:href',     to: 'pages#open_url'
end

app/models/new.rb
class New < ActiveRecord::Base
	has_many :comments, as: :commentable

	validates :title, presence: true, length: { in: 5..25 }, uniqueness: { case_sensitive: false }
	validates :description, presence: true
	validates :body, presence: true
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :admin_user, only: [ :new, :create, :edit, :update, :destroy ]

  def index
    @news = New.paginate(page: params[:page], per_page: 10)
  end

  def show
    @new = New.find(params[:id])
  end

  def new
    @new = New.new
  end

  def create
    @new = New.create(new_params)
    if @new.save
      flash[:success] = 'Новость добавлена'
      redirect_to news_path
    else
      flash[:danger] = 'Ошибка добавления новости'
      render 'new'
    end
  end

  def edit
    @new = New.find(params[:id])
  end

  def update
    @new = New.find(params[:id])
    if @new.update_attributes new_params
      flash[:success] = 'Новость обновлена'
      redirect_to @new
    else
      flash[:danger] = 'Ошибка изменения новости'
      render 'edit'
    end
  end

  def destroy
    New.find(params[:id]).destroy
    flash[:success] = 'Новость удалена'
    redirect_to news_path
  end

  private

    def new_params
      params.require(:new).permit(:title, :description, :body, :enabled)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>
<div class="form-group">
  <%= f.label :title, 'Загаловок', class: 'col-lg-3 control-label' %>
  <div class="col-lg-9">
    <%= f.text_field :title, placeholder: 'Заголовок', class: 'form-control' %>
  </div>
</div>
<div class="form-group">
  <%= f.label :description, 'Описание', class: 'col-lg-3 control-label' %>
  <div class="col-lg-9">
    <%= f.text_area :description, placeholder: 'Описание', class: 'form-control' %>
  </div>
</div>
<div class="form-group">
  <div class="col-lg-9 col-lg-offset-3">
    <div class="togglebutton">
      <label>
        <%= f.check_box :enabled %>
        Показывать новость
      </label>
    </div>
  </div>
</div>
<div class="form-group">
  <%= f.label :body, 'Новость', class: 'col-lg-3 control-label' %>
  <div class="col-lg-9">
    <%= f.cktext_area :body, placeholder: 'Новость', class: 'form-control' %>
  </div>
</div>

app/views/news/_new.html.erb
<div class="list-group-item">
  <div class="row-content">
    <h4><%= new.title %></h4>
    <p><%= new.description %></p>
    <%= new.updated_at %>
    <%= link_to 'Просмотр', new, class: 'label label-primary' %>
    <%= link_to 'Изменить', edit_news_path(new), class: 'label label-info' if admin? %>
    <%= link_to 'Удалить', new, method: 'delete', class: 'label label-danger',
                data: { confirm: 'Вы уверены?' } if admin? %>
  </div>
</div>
<div class="list-group-separator"></div>

app/views/news/edit.html.erb
<% provide :title, 'Редактировать новость' %>
<div class="container">
  <div class="form-horizontal">
    <fieldset>
      <legend>Редактирование новости</legend>
      <%= form_for @new do |f| %>
        <%= render 'fields', f: f %>
        <div class="col-lg-9 col-lg-offset-3">
          <%= f.submit 'Применить', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </fieldset>
  </div>
</div>

app/views/news/index.html.erb
<% provide :title, 'Новости' %>
<div class="container">
    <h1>Новости</h1>
    <%= link_to 'Создать', new_news_path, class: 'label label-primary' if admin? %>
    <%= will_paginate %>
    <div class="group-list">
      <%= render @news %>
    </div>
    <%= will_paginate %>
</div>

app/views/news/new.html.erb
<% provide :title, 'Добавить новость' %>
<div class="container">
  <div class="form-horizontal">
    <fieldset>
      <legend>Добавить новость</legend>
      <%= form_for @new do |f| %>
          <%= render 'fields', f: f %>
          <div class="col-lg-9 col-lg-offset-3">
            <%= f.submit 'Создать', class: 'btn btn-primary' %>
          </div>
      <% end %>
    </fieldset>
  </div>
</div>

app/views/news/show.html.erb
<% provide :title, @new.title %>
<div class="container">
  <div class="col-lg-12">
    <h1><%= @new.title %></h1>
    <p><%= @new.description %></p>
    <div>
      <%= render inline: @new.body %>
    </div>
  </div>
  <div class="col-lg-12">
    <%= @new.updated_at %>
    <%= link_to 'Изменить', edit_news_path(@new), class: 'label label-warning' if admin? %>
    <%= link_to 'Изменить', @new, class: 'label label-danger',
                            method: 'delete', data: { confirm: 'Вы уверены?' } if admin? %>
  </div>

  <div class="col-lg-12">
    <%= render 'comments/index', item: @new %>
  </div>
</div>