config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/index'

  mount Ckeditor::Engine => '/ckeditor'
  root 'goods#index'
  resources :users, :pages, :news, :goods
  resources :sessions, only: [ :new, :create, :destroy ]
  resources :categories, only: [ :index, :show, :create, :update, :destroy ]
  resources :carts, only: [ :index, :create, :destroy ]
  resources :orders, only: [ :index, :create, :destroy ]
  resources :images, only: [ :create, :destroy ]
  resources :bookmarks, only: [ :index, :create, :destroy ]
  resources :good_reviews, only: [ :create, :update, :destroy ]
  resources :likes, only: [ :create, :destroy ]
  
  resources :questions, only: [ :index, :create, :update, :destroy ]
  resources :tickets, only: [ :index, :show, :new, :create, :update, :destroy ]

  # Comments
  resources :comments, only: [ :create, :destroy ]

  # Properties
  resources :property_types, only: [ :index, :create, :update, :destroy ]
  resources :properties, only: [ :index, :create, :update, :destroy ]
  resources :property_values, only: [ :create, :update ]
  match '/categories/:cid/properties/:pid', to: 'categories#include', via: 'post'
  match '/categories/:cid/properties/:pid', to: 'categories#exclude', via: 'delete'

  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/search',  to: 'static_pages#search', via: 'get'
  match '/admin',   to: 'static_pages#admin',  via: 'get'

  get '/:href',     to: 'pages#open_url'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  belongs_to :good

  validates :user_id, presence: true
  validates :good_id, presence: true

  before_create { self.price = Good.find(good_id).price }
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :signed_in_user

  def index
    @carts = current_user.carts
  end

  def create
    @cart = current_user.carts.create(cart_params)
    if @cart.save
      flash[:success] = 'Товар добавлен в корзину'
    else
      flash[:danger] = 'Ошибка при добавлении товара'
    end
    redirect_to :back
  end

  def destroy
    current_user.carts.find(params[:id]).destroy
    flash[:success] = 'Товар удален из корзины'
    redirect_to :back
  end

  private

    def cart_params
      params.require(:cart).permit(:good_id)
    end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<tr>
    <td><input type="checkbox" name="order_items[<%= cart.good_id %>][enabled]"></td>
    <td><%= link_to cart.good.name, cart.good %></td>
    <td><%= cart.price %></td>
    <td><input type="number" name="order_items[<%= cart.good_id %>][count]" class="form-control" min="1"></td>
    <td><%= link_to 'Удалить', cart, method: 'delete', class: '' %></td>
</tr>

app/views/carts/index.html.erb
<% provide :title, 'Корзина' %>
<div class="container">
  <h1>Корзина</h1>
  <%= form_tag orders_path, method: 'post' do %>
      <table class="table table-stripped table-hover">
        <thead>
            <th></th>
            <th>Нименование</th>
            <th>Цена</th>
            <th>Количество</th>
            <th>Удалить</th>
        </thead>
        <%= render @carts %>
      </table>
      <%= submit_tag 'Выполнить заказ', class: 'btn btn-primary' %>
      <%= link_to 'Продолжить выбор покупок', :back, class: 'btn btn-default' %>
  <% end %>
</div>