config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/index'

  mount Ckeditor::Engine => '/ckeditor'
  root 'goods#index'
  resources :users, :pages, :news, :goods
  resources :sessions, only: [ :new, :create, :destroy ]
  resources :categories, only: [ :index, :show, :create, :update, :destroy ]
  resources :carts, only: [ :index, :create, :destroy ]
  resources :orders, only: [ :index, :create, :destroy ]
  resources :images, only: [ :create, :destroy ]
  resources :bookmarks, only: [ :index, :create, :destroy ]
  resources :good_reviews, only: [ :create, :update, :destroy ]
  resources :likes, only: [ :create, :destroy ]
  
  resources :questions, only: [ :index, :create, :update, :destroy ]
  resources :tickets, only: [ :index, :show, :new, :create, :update, :destroy ]

  # Comments
  resources :comments, only: [ :create, :destroy ]

  # Properties
  resources :property_types, only: [ :index, :create, :update, :destroy ]
  resources :properties, only: [ :index, :create, :update, :destroy ]
  resources :property_values, only: [ :create, :update ]
  match '/categories/:cid/properties/:pid', to: 'categories#include', via: 'post'
  match '/categories/:cid/properties/:pid', to: 'categories#exclude', via: 'delete'

  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/search',  to: 'static_pages#search', via: 'get'
  match '/admin',   to: 'static_pages#admin',  via: 'get'

  get '/:href',     to: 'pages#open_url'
end

app/models/good.rb
class Good < ActiveRecord::Base
  belongs_to :category
  has_many :images, dependent: :destroy
  has_many :good_reviews, dependent: :destroy
  has_many :comments, as: :commentable
  has_many :property_values, dependent: :destroy

  has_many :carts, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :description, presence: true

  before_save { self.price = price.truncate(2) }

  def property_value(property)
    property_values.find_by(property_id: property.id) || self.property_values.create!(property_id: property.id)
  end


end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :signed_in_user, only: [ :new, :create, :edit, :update, :destroy ]
  before_action :admin_user, only: [ :new, :create, :edit, :update, :destroy ]

  def index
    @goods ||= Good.paginate(page: params[:page], per_page: 12)
  end

  def show
    @good = Good.find(params[:id])
  end

  def new
    @good = Good.new
  end

  def create
    @good = Good.create good_params
    if @good.save
      flash[:success] = 'Товар успешно создан'
      redirect_to @good
    else
      flash[:danger] = 'Ошибка при создании товара'
      render 'new'
    end
  end

  def edit
    @good = Good.find(params[:id])
  end

  def update
    @good = Good.find(params[:id])
    if @good.update_attributes good_params
      flash[:success] = 'Товар обновлен'
      redirect_to @good
    else
      flash[:danger] = 'Ошибка обновления товара'
      render 'edit'
    end
  end

  def destroy
    Good.find(params[:id]).destroy
    flash[:success] = 'Товар удален'
    redirect_to goods_path
  end

  private

    def good_params
      params.require(:good).permit(:name, :description, :art, :price, :enabled, :count, :category_id)
    end

end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/views/goods/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>
<div class="form-group">
  <%= f.label :name, 'Наименование', class: 'control-label col-lg-3' %>
  <div class="col-lg-9">
    <%= f.text_field :name, class: 'form-control' %>
  </div>
</div>
<div class="form-group">
  <%= f.label :art, 'Артикул', class: 'control-label col-lg-3' %>
  <div class="col-lg-9">
    <%= f.text_field :art, class: 'form-control' %>
  </div>
</div>
<div class="form-group">
  <%= f.label :price, 'Цена', class: 'control-label col-lg-3' %>
  <div class="col-lg-9">
    <%= f.number_field :price, class: 'form-control' %>
  </div>
</div>
<div class="form-group">
  <%= f.label :count, 'Количество', class: 'control-label col-lg-3' %>
  <div class="col-lg-9">
    <%= f.text_field :count, class: 'form-control' %>
  </div>
</div>
<div class="form-group">
  <%= f.label :category_id, 'Категория', class: 'control-label col-lg-3' %>
  <div class="col-lg-9">
    <%= f.collection_select :category_id, Category.all, :id, :name %>
    <%#= f.text_field :category_id, class: 'form-control' %>
  </div>
</div>
<div class="form-group">
  <%= f.label :name, 'Описание', class: 'control-label col-lg-3' %>
  <div class="col-lg-9">
    <%= f.text_area :description, class: 'form-control' %>
  </div>
</div>

app/views/goods/_good.html.erb
<div class="col-lg-3 col-md-4 col-xs-6">
    <h4><%= link_to good.name, good %></h4>
    <h3><%= good.price %></h3>
    <%= link_to good.category.name, good.category, class: 'label label-info' %>
    <%= render 'shared/cart_btn', good: good %>
    <%= render 'shared/bookmark_btn', good: good %>
    <div>
      <%= link_to 'Изменить', edit_good_path(good), class: 'label label-warning' if admin? %>
      <%= link_to 'Удалить', good, method: 'delete',
                  data: { confirm: 'Вы уверены?' }, class: 'label label-danger' if admin? %>
    </div>
</div>

app/views/goods/_property.html.erb
<% if admin? %>
	<%= form_for property_value do |f| %>
		<%= f.hidden_field :good_id %>
		<%= f.hidden_field :property_id %>
		<p>
			<%= property_value.property.name %>: 
			<%= property_value.value %>
		</p>
		<%= render inline: property_value.property.property_type.view, locals: { f: f } %>
		<%= f.submit 'Принять', class: 'btn btn-xs btn-primary' %>
	<% end %>
<% else %>
	<%= property_value.property.name %>: <%= property_value.value %>
<% end %>

app/views/goods/_review_form.html.erb
<div class="form form-horizontal">
  <%= form_for current_user.review(@good) do |f| %>
      <fieldset>
        <legend>Ваш отзыв</legend>
        <%= render 'shared/error_messages', object: f.object %>
        <%= f.hidden_field :good_id, value: good.id %>
        <div class="form-group">
          <%= f.label :title, 'Заголовок', class: 'control-label col-lg-3' %>
          <div class="col-lg-9">
            <%= f.text_field :title, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :mark, 'Оценка', class: 'control-label col-lg-3' %>
          <div class="col-lg-9">
            <%= f.number_field :mark, min: 0, max: 10, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :body, 'Отзыв', class: 'control-label col-lg-3' %>
          <div class="col-lg-9">
            <%= f.text_area :body, class: 'form-control' %>
          </div>
        </div>
        <div class="col-lg-9 col-lg-offset-3">
          <%= f.submit 'Отправить', class: 'btn btn-primary' %>
        </div>
      </fieldset>
  <% end %>
</div>

app/views/goods/_reviews.html.erb
<div class="list-group">
  <% reviews.each do |review| %>
      <div class="list-group-item">
        <div class="row-picture">
          <%= gravatar_for review.user, size: 250, class: 'circle' %>
        </div>
        <div class="row-content">
          <h4><%= review.title %><%= review.mark %></h4>
          <p><%= review.body %></p>
          <div class="col-lg-12">
            <%= review.updated_at %>
            <%= link_to review.user.login, review.user, class: 'label label-info' %>
            <%= link_to 'delete', review, class: 'label label-danger', method: 'delete',
                        data: { confirm: 'Вы уверены?' } if admin? %>
          </div>
        </div>
      </div>
      <div class="list-group-separator"></div>
  <% end %>
</div>

app/views/goods/edit.html.erb
<% provide :title, 'Изменение товара' %>
<div class="container">
  <div class="form-horizontal">
    <%= form_for @good do |f| %>
        <%= render 'fields', f: f %>
        <div class="col-lg-9 col-lg-offset-3">
          <%= f.submit 'Применить', class: 'btn btn-primary' %>
        </div>
    <% end %>
  </div>
  <div class="form-horizontal col-lg-12">
    <%= form_for Image.new do |f| %>
        <fieldset>
          <legend>Новое изображение</legend>
          <%= render 'shared/error_messages', object: f.object %>
          <%= f.hidden_field :good_id, value: @good.id %>
          <div class="form-group">
            <%= f.label :title, 'Заголовок', class: 'control-label col-lg-3' %>
            <div class="col-lg-9">
              <%= f.text_field :title, class: 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :alt, 'Альтернативный текст', class: 'control-label col-lg-3' %>
            <div class="col-lg-9">
              <%= f.text_field :alt, class: 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :alt, 'Изображение', class: 'control-label col-lg-3' %>
            <div class="col-lg-9">
              <input type="text" readonly="" class="form-control floating-label" placeholder="Browse...">
              <%= f.file_field :path %>
            </div>
          </div>
          <div class="col-lg-9 col-lg-offset-3">
            <%= f.submit 'Загрузить', class: 'btn btn-primary' %>
          </div>
        </fieldset>
    <% end %>
  </div>
  <div class="col-lg-12">
    <% @good.images.each do |img| %>
        <div class="col-lg-3">
          <%= image_tag img.path.url(:thumb) %>
          <%= link_to 'Удалить', img, method: 'delete', class: 'label label-danger',
                      data: { confirm: 'Вы уверены?' } %>
        </div>
    <% end %>
  </div>
</div>

app/views/goods/index.html.erb
<%= provide :title, 'Каталог' %>
<div class="container">
  <h1>Каталог</h1>
  <%= will_paginate @goods %>
  <div class="col-lg-12">
    <%= render @goods %>
  </div>
  <%= will_paginate @goods %>
</div>

app/views/goods/new.html.erb
<% provide :title, 'Новый товар' %>
<div class="container">
  <div class="form-horizontal">
    <%= form_for @good do |f| %>
        <%= render 'fields', f: f %>
        <div class="col-lg-9 col-lg-offset-3">
          <%= f.submit 'Создать', class: 'btn btn-primary' %>
        </div>
    <% end %>
  </div>
</div>

app/views/goods/show.html.erb
<% provide :title, @good.name %>
<div class="container">
  <h1><%= @good.name %></h1>
  <div class="col-lg-6">
    <% @good.images.each do |img| %>
      <%= image_tag img.path.url(:thumb) %>
    <% end %>
  </div>
  <div class="col-lg-6">
    <h2><%= @good.price %></h2>
    <%= render 'shared/cart_btn', good: @good %>
    <%= render 'shared/bookmark_btn', good: @good %>
    <%= render 'shared/like_btn', good: @good %>
    <p><%= @good.description %></p>
    <div class="col-lg-12">
      <% @good.category.all_properties.each do |property| %>
        <%= render 'property', property_value: @good.property_value(property) %>
      <% end %>
    </div>
  </div>
  <div class="col-lg-12">
    <div class="btn-group">
      <%= link_to 'Изменить', edit_good_path(@good), class: 'label label-info' if admin? %>
      <%= link_to 'Удалить', @good, method: 'delete', class: 'label label-danger', data: { confirm: 'Вы уверены?' } if admin? %>
    </div>
  </div>
  <div class="col-lg-12">
    <ul class="nav nav-tabs" style="margin-bottom: 15px;">
      <li class="active"><a href="#comments" data-toggle="tab">Комментарии</a></li>
      <li><a href="#reviews" data-toggle="tab">Отзывы</a></li>
    </ul>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane fade active in" id="comments">
        <%= render 'comments/index', item: @good %>
      </div>
      <div class="tab-pane fade" id="reviews">
        <%= render 'review_form', good: @good if signed_in? %>
        <%= render 'reviews', reviews: @good.good_reviews %>
      </div>
    </div>
  </div>
</div>